-- v1.19 — Shelf-life directory expansion
-- ==============================================================
-- Adds two columns to the existing `foodkeeper_shelf_life` table so
-- non-FoodKeeper rows can carry source attribution, then bulk-inserts
-- the 122 rows from `data/shelf_life_extended.json` (FDA, FSIS, NCHFP,
-- Cooperative Extension Service, manufacturer guidance).
--
-- Constraint: FoodKeeper is authoritative for any item it covers. The
-- extended JSON has already been deduped against FoodKeeper at the
-- build-script layer (`scripts/build_shelf_life_pages.py`). This
-- migration uses `ON CONFLICT (id) DO NOTHING` for belt-and-suspenders
-- safety — re-running this migration won't overwrite FoodKeeper rows.
--
-- The build script tags FoodKeeper rows with source='USDA FoodKeeper'
-- at render time; this migration writes the same default for existing
-- rows so the iOS + web `lookupShelfLife()` lookups can show source
-- attribution in the UI in a future iteration.
--
-- Idempotent: re-running is safe (ADD COLUMN IF NOT EXISTS, ON CONFLICT
-- DO NOTHING).
-- ==============================================================

-- 1. Schema additions — provenance fields.

alter table public.foodkeeper_shelf_life
    add column if not exists source     text not null default 'USDA FoodKeeper',
    add column if not exists source_url text;

comment on column public.foodkeeper_shelf_life.source     is 'v1.19 — Short label of the publication this row came from. USDA FoodKeeper (default), FDA, FSIS, NCHFP, Extension, Manufacturer.';
comment on column public.foodkeeper_shelf_life.source_url is 'v1.19 — Canonical URL for the source publication. NULL for general manufacturer guidance.';

-- Backfill source_url for existing FoodKeeper rows that pre-date this column.
update public.foodkeeper_shelf_life
   set source_url = 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/foodkeeper-app'
 where source = 'USDA FoodKeeper'
   and source_url is null;

-- 2. Bulk-insert the 122 extended rows. Hand-loaded values mirror
--    `data/shelf_life_extended.json` (post-dedup). IDs are 10001+ so
--    they don't collide with FoodKeeper IDs (which range 2–684).
--
-- Categories use FoodKeeper's category strings so the existing
-- `ok2eat_category` generated column maps correctly.

insert into public.foodkeeper_shelf_life
  (id, name, subtitle, category, subcategory, keywords,
   pantry_min_days, pantry_max_days, pantry_open_min_days, pantry_open_max_days,
   fridge_min_days, fridge_max_days, fridge_open_min_days, fridge_open_max_days,
   freezer_min_days, freezer_max_days,
   tips, source, source_url)
values
  -- Asian pantry
  (10001, 'Miso paste', 'white, red, or mixed', 'Condiments, Sauces & Canned Goods', 'Asian pantry', 'miso paste fermented soybean japanese shiro aka',
    NULL, NULL, NULL, NULL,  365, 730, 365, 730,  NULL, NULL,
    'Refrigerate after opening. White (shiro) miso has the shortest fridge life; red (aka) and barley miso last longest.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10002, 'Gochujang', 'Korean chili paste', 'Condiments, Sauces & Canned Goods', 'Asian pantry', 'gochujang korean fermented chili paste',
    NULL, NULL, NULL, NULL,  365, 730, 365, 730,  NULL, NULL,
    'Refrigerate after opening. Salt and fermentation give it a very long fridge life.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10003, 'Doenjang', 'Korean fermented soybean paste', 'Condiments, Sauces & Canned Goods', 'Asian pantry', 'doenjang korean fermented soybean paste',
    NULL, NULL, NULL, NULL,  365, 730, 365, 730,  NULL, NULL,
    'Refrigerate after opening. Color darkens with age — normal.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10004, 'Sambal oelek', NULL, 'Condiments, Sauces & Canned Goods', 'Asian pantry', 'sambal oelek indonesian chili paste',
    NULL, NULL, NULL, NULL,  180, 365, 180, 365,  NULL, NULL,
    'Refrigerate after opening. High salt + acid content gives long fridge life.', 'Manufacturer', NULL),
  (10005, 'Harissa paste', NULL, 'Condiments, Sauces & Canned Goods', 'North African pantry', 'harissa north african tunisian moroccan chili paste',
    NULL, NULL, NULL, NULL,  90, 180, 90, 180,  NULL, NULL,
    'Refrigerate after opening. Drizzle a thin layer of olive oil on top to extend life.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10006, 'Sriracha sauce', NULL, 'Condiments, Sauces & Canned Goods', 'Asian pantry', 'sriracha hot sauce thai chili garlic',
    730, 1095, NULL, NULL,  730, 1095, 365, 730,  NULL, NULL,
    'Shelf-stable unopened. Refrigeration after opening is optional but preserves color and flavor longer.', 'Manufacturer', NULL),
  (10007, 'Fish sauce', 'nam pla / nuoc mam', 'Condiments, Sauces & Canned Goods', 'Asian pantry', 'fish sauce nam pla nuoc mam vietnamese thai',
    1095, 1460, 730, 1095,  1095, 1460, 730, 1460,  NULL, NULL,
    'Shelf-stable. Color darkens over time — normal.', 'Manufacturer', NULL),
  (10010, 'Tamari', 'gluten-free soy sauce', 'Condiments, Sauces & Canned Goods', 'Asian pantry', 'tamari gluten free soy sauce japanese',
    730, 1095, NULL, NULL,  730, 1460, 730, 1095,  NULL, NULL,
    'Refrigeration after opening optional but preserves nuanced flavor.', 'Manufacturer', NULL),
  (10011, 'Ponzu sauce', NULL, 'Condiments, Sauces & Canned Goods', 'Asian pantry', 'ponzu citrus soy japanese sauce',
    NULL, NULL, NULL, NULL,  180, 365, 90, 180,  NULL, NULL,
    'Refrigerate after opening — the citrus juice has a shorter life than plain soy sauce.', 'Manufacturer', NULL),
  -- Mediterranean / specialty
  (10014, 'Labneh', 'strained yogurt', 'Dairy Products & Eggs', 'Specialty dairy', 'labneh strained yogurt middle eastern cheese',
    NULL, NULL, NULL, NULL,  14, 21, 7, 10,  NULL, NULL,
    'Higher fat + strained whey gives labneh a longer fridge life than regular yogurt.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10015, 'Kimchi', 'fermented cabbage', 'Deli & Prepared Foods', 'Fermented foods', 'kimchi korean fermented cabbage napa',
    NULL, NULL, NULL, NULL,  90, 180, 60, 180,  NULL, NULL,
    'Fermentation continues in the fridge — kimchi becomes more sour over time.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10016, 'Sauerkraut', 'refrigerated, live cultures', 'Deli & Prepared Foods', 'Fermented foods', 'sauerkraut fermented cabbage refrigerated probiotic',
    NULL, NULL, NULL, NULL,  120, 180, 90, 180,  NULL, NULL,
    'Refrigerated unpasteurized sauerkraut keeps fermenting and becomes more sour.', 'NCHFP', 'https://nchfp.uga.edu/'),
  -- Tofu varieties
  (10017, 'Tofu', 'firm or extra firm, water-packed', 'Vegetarian Proteins', 'Soy products', 'tofu firm extra firm water packed soy',
    NULL, NULL, NULL, NULL,  7, 10, 3, 5,  90, 180,
    'Change the water daily after opening to extend life. Freezing changes the texture.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10020, 'Seitan', 'wheat gluten', 'Vegetarian Proteins', 'Wheat products', 'seitan wheat gluten wheat meat',
    NULL, NULL, NULL, NULL,  7, 10, 3, 5,  90, 180,
    'Store in its broth or moist wrapping to prevent drying.', 'Extension', 'https://extension.psu.edu/food-safety'),
  -- Dried seaweed
  (10021, 'Nori sheets', 'dried seaweed', 'Shelf Stable Foods', 'Dried seaweed', 'nori dried seaweed sushi japanese',
    365, 730, 60, 90,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Once opened, transfer to an airtight container with a silica packet to keep crisp.', 'Manufacturer', NULL),
  (10022, 'Wakame', 'dried seaweed', 'Shelf Stable Foods', 'Dried seaweed', 'wakame dried seaweed japanese miso soup',
    365, 1095, 365, 730,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Store in an airtight container.', 'Manufacturer', NULL),
  -- Noodles
  (10023, 'Rice noodles', 'dry', 'Grains, Beans & Pasta', 'Asian noodles', 'rice noodles dry vermicelli pad thai pho',
    730, 1095, 365, 730,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Store in an airtight container after opening.', 'Manufacturer', NULL),
  (10024, 'Ramen noodles', 'fresh refrigerated', 'Grains, Beans & Pasta', 'Asian noodles', 'ramen noodles fresh refrigerated japanese',
    NULL, NULL, NULL, NULL,  14, 21, 3, 5,  60, 90,
    'Best texture within 5 days of opening.', 'Manufacturer', NULL),
  (10025, 'Udon noodles', 'fresh', 'Grains, Beans & Pasta', 'Asian noodles', 'udon noodles fresh japanese wheat',
    NULL, NULL, NULL, NULL,  14, 21, 3, 5,  60, 90,
    'Vacuum-packed udon last to the printed date.', 'Manufacturer', NULL),
  (10026, 'Curry paste', 'Thai red, green, or yellow', 'Condiments, Sauces & Canned Goods', 'Asian pantry', 'curry paste thai red green yellow massaman',
    365, 730, NULL, NULL,  365, 730, 60, 90,  NULL, NULL,
    'Refrigerate after opening. Freezes well in ice cube trays.', 'Manufacturer', NULL),
  -- Modern pantry
  (10027, 'Nutritional yeast', 'flakes or powder', 'Shelf Stable Foods', 'Modern pantry', 'nutritional yeast nooch vegan cheese flavor',
    730, 1095, 365, 730,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Loses potency over time but doesn''t go bad.', 'Manufacturer', NULL),
  (10028, 'Hemp seeds', 'hulled', 'Shelf Stable Foods', 'Modern pantry', 'hemp seeds hulled hemp hearts',
    180, 365, 90, 180,  365, 540, 180, 365,  540, 730,
    'Refrigerate or freeze for longest life — the oils go rancid at room temperature.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10030, 'Flax seeds', 'whole', 'Shelf Stable Foods', 'Modern pantry', 'flax seeds whole flaxseed linseed',
    365, 730, 180, 365,  730, 1095, NULL, NULL,  NULL, NULL,
    'Whole flax seeds last much longer than ground.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10031, 'Flax seeds', 'ground / milled', 'Shelf Stable Foods', 'Modern pantry', 'flax seeds ground milled flaxseed meal',
    30, 60, NULL, NULL,  90, 180, NULL, NULL,  365, 540,
    'Ground flax goes rancid much faster than whole. Refrigerate or freeze immediately.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10032, 'Psyllium husk', NULL, 'Shelf Stable Foods', 'Modern pantry', 'psyllium husk fiber supplement',
    730, 1460, NULL, NULL,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Store away from moisture. Very long shelf life.', 'Manufacturer', NULL),
  (10033, 'Coconut aminos', NULL, 'Condiments, Sauces & Canned Goods', 'Modern pantry', 'coconut aminos soy sauce alternative',
    365, 730, 365, 540,  NULL, NULL, 730, 1095,  NULL, NULL,
    'Refrigeration after opening optional but extends life.', 'Manufacturer', NULL),
  (10034, 'MCT oil', NULL, 'Shelf Stable Foods', 'Cooking oils', 'mct oil medium chain triglycerides coconut',
    730, 1095, 730, 1095,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Resistant to oxidation; very stable.', 'Manufacturer', NULL),
  (10036, 'Coconut oil', 'refined or unrefined', 'Shelf Stable Foods', 'Cooking oils', 'coconut oil refined unrefined virgin',
    730, 1095, 365, 730,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Very stable due to saturated fat content. Solid below 76°F.', 'Manufacturer', NULL),
  (10039, 'Sunflower seed butter', 'SunButter', 'Shelf Stable Foods', 'Nut butters', 'sunflower seed butter sunbutter nut free allergen',
    90, 180, 60, 90,  180, 365, 180, 365,  NULL, NULL,
    'May turn green when reacting with baking soda — safe to eat.', 'Manufacturer', NULL),
  (10040, 'Bone broth', 'refrigerated carton', 'Deli & Prepared Foods', 'Broths', 'bone broth chicken beef refrigerated carton',
    NULL, NULL, NULL, NULL,  14, 30, 5, 7,  90, 180,
    'Once opened, gels when cold — this is the collagen and is normal.', 'Manufacturer', NULL),
  (10041, 'Bone broth', 'shelf-stable Tetra Pak', 'Shelf Stable Foods', 'Broths', 'bone broth shelf stable tetra pak boxed',
    365, 730, NULL, NULL,  NULL, NULL, 5, 7,  90, 180,
    'Refrigerate immediately after opening.', 'Manufacturer', NULL),
  (10042, 'Collagen powder', 'hydrolyzed peptides', 'Shelf Stable Foods', 'Supplements', 'collagen powder hydrolyzed peptides bovine marine',
    730, 1095, 365, 730,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Store away from moisture.', 'Manufacturer', NULL),
  (10043, 'Protein powder', 'whey, plant, or casein', 'Shelf Stable Foods', 'Supplements', 'protein powder whey plant casein isolate concentrate',
    365, 730, 180, 365,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Loses potency past the printed date but generally safe if stored dry.', 'Manufacturer', NULL),
  (10044, 'Stevia', 'powdered or liquid extract', 'Shelf Stable Foods', 'Sweeteners', 'stevia powdered liquid sweetener sugar substitute',
    730, 1460, 730, 1095,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Liquid stevia has alcohol or glycerin as a preservative — very long shelf life.', 'Manufacturer', NULL),
  (10045, 'Monk fruit sweetener', 'powdered', 'Shelf Stable Foods', 'Sweeteners', 'monk fruit sweetener lakanto sugar substitute',
    730, 1095, 365, 730,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Store in an airtight container.', 'Manufacturer', NULL),
  -- Plant milks
  (10046, 'Oat milk', 'refrigerated carton', 'Beverages', 'Plant milks', 'oat milk refrigerated plant milk dairy free',
    NULL, NULL, NULL, NULL,  21, 60, 7, 10,  NULL, NULL,
    'Shake well before each use — separation is normal.', 'FDA', 'https://www.fda.gov/food/buy-store-serve-safe-food/refrigerator-freezer-storage-chart'),
  (10047, 'Oat milk', 'shelf-stable Tetra Pak', 'Shelf Stable Foods', 'Plant milks', 'oat milk shelf stable tetra pak boxed',
    270, 365, NULL, NULL,  NULL, NULL, 7, 10,  NULL, NULL,
    'Refrigerate after opening.', 'Manufacturer', NULL),
  (10048, 'Almond milk', 'refrigerated', 'Beverages', 'Plant milks', 'almond milk refrigerated plant milk dairy free',
    NULL, NULL, NULL, NULL,  21, 60, 7, 10,  NULL, NULL,
    'Separation is normal — shake before use.', 'FDA', 'https://www.fda.gov/food/buy-store-serve-safe-food/refrigerator-freezer-storage-chart'),
  (10051, 'Cashew milk', 'refrigerated', 'Beverages', 'Plant milks', 'cashew milk refrigerated plant milk dairy free',
    NULL, NULL, NULL, NULL,  21, 45, 7, 10,  NULL, NULL,
    'Shake before use.', 'Manufacturer', NULL),
  (10052, 'Coconut milk', 'refrigerated carton, drinking', 'Beverages', 'Plant milks', 'coconut milk drinking refrigerated plant milk',
    NULL, NULL, NULL, NULL,  21, 45, 7, 10,  NULL, NULL,
    'Distinct from canned coconut milk — drinking version is diluted.', 'Manufacturer', NULL),
  -- Plant-based cheese + butter
  (10053, 'Vegan cheese', 'shreds or slices', 'Dairy Products & Eggs', 'Plant-based cheese', 'vegan cheese plant based shreds slices dairy free',
    NULL, NULL, NULL, NULL,  30, 60, 7, 14,  90, 180,
    'Plant-based cheese has a shorter open-life than dairy cheese.', 'Manufacturer', NULL),
  (10054, 'Vegan cream cheese', NULL, 'Dairy Products & Eggs', 'Plant-based cheese', 'vegan cream cheese plant based dairy free spread',
    NULL, NULL, NULL, NULL,  30, 60, 7, 14,  NULL, NULL,
    'Use a clean utensil each time to avoid contamination.', 'Manufacturer', NULL),
  (10055, 'Vegan butter', NULL, 'Dairy Products & Eggs', 'Plant-based dairy', 'vegan butter plant based dairy free margarine',
    NULL, NULL, NULL, NULL,  60, 120, 30, 60,  270, 365,
    'Lower water content than dairy butter — slightly different melting behavior.', 'Manufacturer', NULL),
  (10056, 'Plant-based ground', 'Impossible / Beyond, raw', 'Vegetarian Proteins', 'Plant-based meat', 'plant based ground beef impossible beyond meat alternative',
    NULL, NULL, NULL, NULL,  7, 10, 2, 3,  90, 180,
    'Cook within 3 days of opening.', 'Manufacturer', NULL),
  (10057, 'Plant-based sausage', 'raw', 'Vegetarian Proteins', 'Plant-based meat', 'plant based sausage beyond impossible vegan',
    NULL, NULL, NULL, NULL,  7, 10, 2, 3,  90, 180,
    'Cook to package instructions.', 'Manufacturer', NULL),
  (10058, 'Coconut yogurt', NULL, 'Dairy Products & Eggs', 'Plant-based yogurt', 'coconut yogurt plant based dairy free probiotic',
    NULL, NULL, NULL, NULL,  14, 30, 5, 7,  NULL, NULL,
    'Liquid pooling on the surface is whey — stir back in.', 'Manufacturer', NULL),
  (10059, 'Oat yogurt', NULL, 'Dairy Products & Eggs', 'Plant-based yogurt', 'oat yogurt plant based dairy free',
    NULL, NULL, NULL, NULL,  14, 30, 5, 7,  NULL, NULL,
    'Treat like dairy yogurt once opened.', 'Manufacturer', NULL),
  -- Specialty produce
  (10060, 'Microgreens', NULL, 'Produce', 'Leafy greens', 'microgreens sprouts shoots baby greens',
    NULL, NULL, NULL, NULL,  5, 7, NULL, NULL,  NULL, NULL,
    'Highly perishable. Store with a paper towel to absorb moisture.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10061, 'Alfalfa sprouts', NULL, 'Produce', 'Sprouts', 'alfalfa sprouts raw fresh',
    NULL, NULL, NULL, NULL,  5, 7, NULL, NULL,  NULL, NULL,
    'High-risk for foodborne illness — discard if slimy.', 'FDA', 'https://www.fda.gov/food/buy-store-serve-safe-food/refrigerator-freezer-storage-chart'),
  (10063, 'Pea shoots', NULL, 'Produce', 'Leafy greens', 'pea shoots tendrils baby pea',
    NULL, NULL, NULL, NULL,  5, 7, NULL, NULL,  NULL, NULL,
    'Store wrapped in a damp paper towel.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10066, 'Fennel bulb', NULL, 'Produce', 'Vegetables', 'fennel bulb anise finocchio',
    NULL, NULL, NULL, NULL,  7, 14, NULL, NULL,  NULL, NULL,
    'Trim fronds and stalks before storing.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10067, 'Celeriac', 'celery root', 'Produce', 'Root vegetables', 'celeriac celery root knob',
    NULL, NULL, NULL, NULL,  14, 21, NULL, NULL,  NULL, NULL,
    'Store unwrapped in the crisper. Peel only before use.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10068, 'Parsnip', NULL, 'Produce', 'Root vegetables', 'parsnip white carrot root vegetable',
    NULL, NULL, NULL, NULL,  30, 90, NULL, NULL,  NULL, NULL,
    'Sweeter after a frost. Stores almost as long as carrots.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10069, 'Watercress', NULL, 'Produce', 'Leafy greens', 'watercress peppery greens salad',
    NULL, NULL, NULL, NULL,  3, 5, NULL, NULL,  NULL, NULL,
    'Store stems-down in a glass of water like cut flowers.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10070, 'Frisée', 'curly endive', 'Produce', 'Leafy greens', 'frisee curly endive chicory salad',
    NULL, NULL, NULL, NULL,  5, 7, NULL, NULL,  NULL, NULL,
    'Wrap in a paper towel inside a perforated bag.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10071, 'Escarole', NULL, 'Produce', 'Leafy greens', 'escarole broad leaved endive italian greens',
    NULL, NULL, NULL, NULL,  5, 7, NULL, NULL,  NULL, NULL,
    'Sturdier than lettuce — holds up to cooking.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10073, 'Heirloom tomatoes', NULL, 'Produce', 'Tomatoes', 'heirloom tomatoes vine ripened varieties',
    3, 7, NULL, NULL,  5, 10, NULL, NULL,  NULL, NULL,
    'Best texture and flavor at room temperature.', 'Extension', 'https://extension.psu.edu/food-safety'),
  -- Tropical / exotic fruits
  (10074, 'Dragon fruit', 'pitaya', 'Produce', 'Tropical fruit', 'dragon fruit pitaya pink white',
    3, 5, NULL, NULL,  7, 14, NULL, NULL,  NULL, NULL,
    'Should give slightly when pressed — like a ripe avocado.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10075, 'Passion fruit', NULL, 'Produce', 'Tropical fruit', 'passion fruit maracuya',
    5, 7, NULL, NULL,  14, 21, NULL, NULL,  NULL, NULL,
    'Wrinkled skin means ripe and ready.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10076, 'Persimmon', 'fuyu or hachiya', 'Produce', 'Fruit', 'persimmon fuyu hachiya kaki',
    5, 14, NULL, NULL,  14, 30, NULL, NULL,  NULL, NULL,
    'Fuyu can be eaten firm. Hachiya must be very soft.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10078, 'Pomegranate arils', 'seeds, fresh', 'Produce', 'Fruit', 'pomegranate arils seeds fresh prepared',
    NULL, NULL, NULL, NULL,  5, 7, NULL, NULL,  180, 365,
    'Freeze in a single layer first, then bag.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10079, 'Lychee', 'fresh', 'Produce', 'Tropical fruit', 'lychee fresh asian tropical fruit',
    NULL, NULL, NULL, NULL,  7, 14, NULL, NULL,  NULL, NULL,
    'Refrigerate immediately — they lose flavor at room temp within hours.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10080, 'Yuzu', 'fresh fruit', 'Produce', 'Citrus', 'yuzu japanese citrus fruit',
    NULL, NULL, NULL, NULL,  14, 21, NULL, NULL,  NULL, NULL,
    'Use peel for zest immediately when ripe.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10082, 'Galangal', 'Thai ginger', 'Produce', 'Aromatics', 'galangal thai ginger aromatic root',
    NULL, NULL, NULL, NULL,  14, 30, NULL, NULL,  180, 365,
    'Tougher than ginger — best frozen and grated frozen for use.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10083, 'Kaffir lime leaves', 'fresh', 'Produce', 'Herbs', 'kaffir lime leaves makrut thai',
    NULL, NULL, NULL, NULL,  14, 30, NULL, NULL,  365, 540,
    'Freezes perfectly with no flavor loss.', 'Extension', 'https://extension.psu.edu/food-safety'),
  -- Specialty cheeses
  (10084, 'Halloumi', NULL, 'Dairy Products & Eggs', 'Specialty cheese', 'halloumi cypriot grilling cheese',
    NULL, NULL, NULL, NULL,  60, 365, 14, 21,  180, 365,
    'High salt + brine = very long unopened life.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10085, 'Paneer', NULL, 'Dairy Products & Eggs', 'Specialty cheese', 'paneer indian fresh cheese cottage',
    NULL, NULL, NULL, NULL,  14, 30, 5, 7,  90, 180,
    'Use within a week of opening.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10086, 'Queso fresco', NULL, 'Dairy Products & Eggs', 'Specialty cheese', 'queso fresco mexican fresh cheese',
    NULL, NULL, NULL, NULL,  14, 30, 5, 7,  NULL, NULL,
    'Most queso fresco is pasteurized in the US.', 'FSIS', 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation'),
  (10087, 'Burrata', NULL, 'Dairy Products & Eggs', 'Specialty cheese', 'burrata italian fresh mozzarella cream',
    NULL, NULL, NULL, NULL,  5, 7, 2, 3,  NULL, NULL,
    'Best within 48 hours of opening.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10088, 'Mascarpone', NULL, 'Dairy Products & Eggs', 'Specialty cheese', 'mascarpone italian cream cheese tiramisu',
    NULL, NULL, NULL, NULL,  14, 21, 5, 7,  NULL, NULL,
    'Higher fat than American cream cheese — separates if frozen.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10089, 'Manchego', NULL, 'Dairy Products & Eggs', 'Specialty cheese', 'manchego spanish sheep milk hard cheese',
    NULL, NULL, NULL, NULL,  60, 180, 30, 60,  NULL, NULL,
    'Hard cheese — small mold spots can be cut off with a 1-inch margin.', 'FSIS', 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation'),
  (10090, 'Taleggio', NULL, 'Dairy Products & Eggs', 'Specialty cheese', 'taleggio italian washed rind soft cheese',
    NULL, NULL, NULL, NULL,  14, 30, 7, 10,  NULL, NULL,
    'Smells stronger than it tastes.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10091, 'Fontina', NULL, 'Dairy Products & Eggs', 'Specialty cheese', 'fontina italian alpine cheese',
    NULL, NULL, NULL, NULL,  30, 90, 21, 30,  NULL, NULL,
    'Wrap in parchment then loose plastic.', 'FSIS', 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation'),
  (10092, 'Boursin', 'garlic & herb spread', 'Dairy Products & Eggs', 'Specialty cheese', 'boursin garlic herb cheese spread french',
    NULL, NULL, NULL, NULL,  30, 60, 7, 14,  NULL, NULL,
    'Use a clean knife each time.', 'Manufacturer', NULL),
  -- Fermented + modern beverages
  (10093, 'Kombucha', 'refrigerated, raw', 'Beverages', 'Fermented drinks', 'kombucha refrigerated raw fermented tea probiotic',
    NULL, NULL, NULL, NULL,  60, 120, 7, 14,  NULL, NULL,
    'Continues fermenting in the fridge — flavor gets more vinegary over time.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10094, 'Water kefir', NULL, 'Beverages', 'Fermented drinks', 'water kefir tibicos fermented drink probiotic',
    NULL, NULL, NULL, NULL,  30, 60, 5, 7,  NULL, NULL,
    'Slight pressure buildup is normal.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10095, 'Cold brew coffee', 'bottled, refrigerated', 'Beverages', 'Coffee', 'cold brew coffee bottled refrigerated',
    NULL, NULL, NULL, NULL,  14, 21, 7, 10,  NULL, NULL,
    'Once opened, use within a week.', 'Manufacturer', NULL),
  (10096, 'Cold brew coffee', 'homemade', 'Beverages', 'Coffee', 'cold brew coffee homemade concentrate',
    NULL, NULL, NULL, NULL,  7, 14, NULL, NULL,  NULL, NULL,
    'Strain the grounds out before storing.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10097, 'Sparkling water', 'unflavored or flavored', 'Beverages', 'Carbonated water', 'sparkling water seltzer la croix flavored carbonated',
    270, 365, NULL, NULL,  NULL, NULL, 1, 2,  NULL, NULL,
    'Safe indefinitely, but goes flat fast once opened.', 'Manufacturer', NULL),
  (10098, 'Coconut water', 'refrigerated, fresh', 'Beverages', 'Functional drinks', 'coconut water refrigerated fresh raw',
    NULL, NULL, NULL, NULL,  7, 14, 1, 2,  NULL, NULL,
    'Pink tint is normal in fresh coconut water — natural antioxidant reaction.', 'Manufacturer', NULL),
  (10100, 'Matcha', 'powdered green tea', 'Beverages', 'Tea', 'matcha green tea powder japanese',
    365, 540, 30, 60,  NULL, NULL, 60, 120,  NULL, NULL,
    'Loses color and flavor fast after opening.', 'Manufacturer', NULL),
  (10101, 'Chai concentrate', 'refrigerated', 'Beverages', 'Tea', 'chai concentrate refrigerated indian spiced tea',
    NULL, NULL, NULL, NULL,  14, 30, 7, 10,  NULL, NULL,
    'Dilute 1:1 with milk for a chai latte.', 'Manufacturer', NULL),
  (10102, 'Energy drink', 'Red Bull, Monster, Celsius, etc.', 'Beverages', 'Functional drinks', 'energy drink red bull monster celsius',
    540, 730, NULL, NULL,  NULL, NULL, 1, 2,  NULL, NULL,
    'Drink within 2 days of opening.', 'Manufacturer', NULL),
  (10103, 'Sports drink', 'Gatorade, Powerade', 'Beverages', 'Functional drinks', 'sports drink gatorade powerade electrolyte',
    270, 365, NULL, NULL,  NULL, NULL, 2, 3,  NULL, NULL,
    'Refrigerate after opening.', 'Manufacturer', NULL),
  -- Prepared / deli foods
  (10104, 'Refrigerated pesto', 'fresh basil', 'Deli & Prepared Foods', 'Sauces', 'pesto fresh refrigerated basil parmesan',
    NULL, NULL, NULL, NULL,  14, 30, 5, 7,  90, 180,
    'Drizzle oil on top to prevent oxidation. Freezes well in ice cube trays.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10105, 'Refrigerated marinara', 'fresh', 'Deli & Prepared Foods', 'Sauces', 'marinara fresh refrigerated tomato sauce',
    NULL, NULL, NULL, NULL,  14, 21, 5, 7,  NULL, NULL,
    'Different from shelf-stable jarred — refrigerated has a much shorter life.', 'Manufacturer', NULL),
  (10106, 'Refrigerated salsa', 'fresh, deli case', 'Deli & Prepared Foods', 'Sauces', 'salsa fresh refrigerated pico de gallo deli',
    NULL, NULL, NULL, NULL,  14, 21, 5, 7,  NULL, NULL,
    'Fresh salsa tastes best within 3 days of opening.', 'Manufacturer', NULL),
  (10107, 'Refrigerated guacamole', NULL, 'Deli & Prepared Foods', 'Sauces', 'guacamole refrigerated fresh avocado dip',
    NULL, NULL, NULL, NULL,  7, 14, 2, 3,  NULL, NULL,
    'Browning is oxidation, not spoilage — top layer can be scraped off.', 'Manufacturer', NULL),
  (10109, 'Coleslaw', 'deli, mayo-based', 'Deli & Prepared Foods', 'Prepared salads', 'coleslaw deli prepared mayo cabbage',
    NULL, NULL, NULL, NULL,  5, 7, 3, 5,  NULL, NULL,
    'Liquid pooling at the bottom is normal — cabbage releases water.', 'FSIS', 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation'),
  (10110, 'Macaroni salad', 'deli, mayo-based', 'Deli & Prepared Foods', 'Prepared salads', 'macaroni salad deli prepared mayo pasta',
    NULL, NULL, NULL, NULL,  5, 7, 3, 5,  NULL, NULL,
    'Same 2-hour room-temp rule as other mayo-based salads.', 'FSIS', 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation'),
  (10111, 'Fresh pasta', 'filled — ravioli, tortellini', 'Grains, Beans & Pasta', 'Fresh pasta', 'fresh pasta filled ravioli tortellini stuffed',
    NULL, NULL, NULL, NULL,  14, 60, 3, 5,  60, 90,
    'Cooked filled pasta freezes well; cook from frozen.', 'Manufacturer', NULL),
  (10113, 'Pizza dough', 'refrigerated, raw', 'Deli & Prepared Foods', 'Refrigerated dough', 'pizza dough refrigerated fresh raw',
    NULL, NULL, NULL, NULL,  7, 14, NULL, NULL,  90, 180,
    'Let come to room temperature 1 hour before shaping.', 'Manufacturer', NULL),
  (10116, 'Sushi', 'store-bought, refrigerated', 'Deli & Prepared Foods', 'Prepared meals', 'sushi store bought refrigerated grocery deli',
    NULL, NULL, NULL, NULL,  1, 1, NULL, NULL,  NULL, NULL,
    'Best eaten the same day. Never freeze.', 'FSIS', 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation'),
  (10117, 'Cold-pressed juice', 'HPP / high-pressure processed', 'Beverages', 'Juice', 'cold pressed juice hpp high pressure refrigerated',
    NULL, NULL, NULL, NULL,  30, 45, 2, 3,  NULL, NULL,
    'Separation is normal — shake before drinking.', 'Manufacturer', NULL),
  (10118, 'Cold-pressed juice', 'raw, unpasteurized', 'Beverages', 'Juice', 'cold pressed juice raw unpasteurized fresh',
    NULL, NULL, NULL, NULL,  3, 5, NULL, NULL,  NULL, NULL,
    'Best within 72 hours. High-risk populations should avoid raw juice.', 'FDA', 'https://www.fda.gov/food/buy-store-serve-safe-food/refrigerator-freezer-storage-chart'),
  -- Frozen prepared
  (10119, 'Frozen pizza', NULL, 'Food Purchased Frozen', 'Frozen prepared', 'frozen pizza prepared meal',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  90, 540,
    'Quality holds best at 0°F or below.', 'FSIS', 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation'),
  (10120, 'Frozen burrito', NULL, 'Food Purchased Frozen', 'Frozen prepared', 'frozen burrito prepared meal mexican',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  90, 365,
    'Cook from frozen — thawing makes the tortilla soggy.', 'FSIS', 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation'),
  (10121, 'Frozen dumplings', 'potstickers, gyoza, wontons', 'Food Purchased Frozen', 'Frozen prepared', 'frozen dumplings potstickers gyoza wontons chinese',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  180, 365,
    'Cook from frozen — don''t thaw or the skins tear.', 'Manufacturer', NULL),
  (10122, 'Frozen waffles', NULL, 'Food Purchased Frozen', 'Frozen prepared', 'frozen waffles toaster eggo',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  180, 365,
    'Toast or microwave from frozen.', 'Manufacturer', NULL),
  (10123, 'Frozen acai bowl', NULL, 'Food Purchased Frozen', 'Frozen prepared', 'frozen acai bowl smoothie superfood',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  180, 365,
    'Blend or thaw slightly before eating.', 'Manufacturer', NULL),
  (10124, 'Frozen breakfast sandwich', 'egg + cheese + meat on muffin', 'Food Purchased Frozen', 'Frozen prepared', 'frozen breakfast sandwich jimmy dean egg cheese',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  90, 270,
    'Microwave from frozen.', 'Manufacturer', NULL),
  -- More dairy
  (10125, 'Whipped cream cheese', 'tub', 'Dairy Products & Eggs', 'Cream cheese', 'whipped cream cheese tub philadelphia',
    NULL, NULL, NULL, NULL,  30, 60, 14, 21,  NULL, NULL,
    'Mold spots mean discard the whole tub.', 'FSIS', 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation'),
  (10127, 'Skyr', 'Icelandic strained yogurt', 'Dairy Products & Eggs', 'Yogurt', 'skyr icelandic yogurt strained high protein',
    NULL, NULL, NULL, NULL,  14, 30, 5, 7,  NULL, NULL,
    'Strained whey may pool — stir back in.', 'Manufacturer', NULL),
  (10129, 'Crème fraîche', NULL, 'Dairy Products & Eggs', 'Cultured dairy', 'creme fraiche cultured cream french',
    NULL, NULL, NULL, NULL,  14, 21, 7, 10,  NULL, NULL,
    'Higher fat than sour cream — won''t curdle when heated.', 'Manufacturer', NULL),
  -- Pre-cut produce
  (10131, 'Bagged salad', 'pre-washed, sealed', 'Produce', 'Pre-cut produce', 'bagged salad pre washed mixed greens spring mix',
    NULL, NULL, NULL, NULL,  7, 10, 3, 5,  NULL, NULL,
    'Once opened, transfer to a container with a paper towel.', 'FDA', 'https://www.fda.gov/food/buy-store-serve-safe-food/refrigerator-freezer-storage-chart'),
  (10132, 'Pre-cut fruit', 'melon, pineapple, mango', 'Produce', 'Pre-cut produce', 'pre cut fruit melon pineapple mango deli',
    NULL, NULL, NULL, NULL,  5, 7, 2, 3,  NULL, NULL,
    'Cut fruit has a much shorter life than whole.', 'FDA', 'https://www.fda.gov/food/buy-store-serve-safe-food/refrigerator-freezer-storage-chart'),
  (10133, 'Pre-cut vegetables', 'stir-fry mix, fajita mix', 'Produce', 'Pre-cut produce', 'pre cut vegetables stir fry fajita mix prepared',
    NULL, NULL, NULL, NULL,  5, 7, 2, 3,  NULL, NULL,
    'Best used within 3 days of opening.', 'FDA', 'https://www.fda.gov/food/buy-store-serve-safe-food/refrigerator-freezer-storage-chart'),
  (10134, 'Riced cauliflower', 'refrigerated, raw', 'Produce', 'Pre-cut produce', 'riced cauliflower refrigerated raw low carb',
    NULL, NULL, NULL, NULL,  5, 7, 2, 3,  180, 365,
    'Sulfurous smell after a few days is normal cauliflower aging.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10135, 'Spiralized zucchini', 'zoodles, refrigerated', 'Produce', 'Pre-cut produce', 'spiralized zucchini zoodles refrigerated low carb pasta',
    NULL, NULL, NULL, NULL,  3, 5, 1, 2,  NULL, NULL,
    'Drain off any liquid pooling — releases water as it sits.', 'Extension', 'https://extension.psu.edu/food-safety'),
  -- Baked goods
  (10136, 'Croissant', 'bakery, fresh', 'Baked Goods', 'Pastries', 'croissant french bakery pastry butter',
    2, 3, NULL, NULL,  5, 7, NULL, NULL,  60, 90,
    'Best the day of. Refresh stale croissants at 350°F for 5 minutes.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10137, 'Sourdough bread', 'artisan, no preservatives', 'Baked Goods', 'Bread', 'sourdough bread artisan no preservatives natural',
    3, 5, NULL, NULL,  NULL, NULL, NULL, NULL,  90, 180,
    'Don''t refrigerate — accelerates staling.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10138, 'Brioche', NULL, 'Baked Goods', 'Bread', 'brioche french enriched bread butter eggs',
    3, 5, NULL, NULL,  7, 10, NULL, NULL,  60, 90,
    'Higher fat = stays softer longer than lean bread.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10139, 'Naan', 'fresh, refrigerated', 'Baked Goods', 'Flatbread', 'naan indian flatbread fresh refrigerated',
    NULL, NULL, NULL, NULL,  7, 14, NULL, NULL,  60, 90,
    'Warm in a dry pan or oven to refresh.', 'Manufacturer', NULL),
  (10140, 'Pita bread', NULL, 'Baked Goods', 'Flatbread', 'pita bread middle eastern flatbread pocket',
    5, 7, NULL, NULL,  14, 21, NULL, NULL,  60, 90,
    'Stays softer in the freezer than the fridge.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10141, 'Tortilla', 'flour', 'Baked Goods', 'Flatbread', 'tortilla flour wheat mexican wrap',
    7, 14, NULL, NULL,  21, 60, NULL, NULL,  180, 270,
    'Mold appears quickly at room temp — refrigerate if you won''t finish within a week.', 'Manufacturer', NULL),
  (10142, 'Tortilla', 'corn', 'Baked Goods', 'Flatbread', 'tortilla corn mexican wrap masa',
    5, 10, NULL, NULL,  30, 60, NULL, NULL,  180, 270,
    'Drier and shorter-lived than flour.', 'Manufacturer', NULL),
  (10143, 'English muffin', NULL, 'Baked Goods', 'Bread', 'english muffin breakfast thomas',
    5, 7, NULL, NULL,  14, 21, NULL, NULL,  60, 90,
    'Split with a fork before toasting (not a knife).', 'Manufacturer', NULL),
  (10145, 'Scones', 'bakery', 'Baked Goods', 'Pastries', 'scones bakery british biscuit pastry',
    2, 3, NULL, NULL,  5, 7, NULL, NULL,  60, 90,
    'Texture suffers in the fridge — freeze if you can''t finish in a few days.', 'Extension', 'https://extension.psu.edu/food-safety'),
  -- Sweeteners + condiments
  (10146, 'Maple syrup', 'pure', 'Condiments, Sauces & Canned Goods', 'Sweeteners', 'maple syrup pure grade a vermont',
    540, 1095, 30, 60,  NULL, NULL, 365, 730,  1825, 3650,
    'Refrigerate after opening to prevent mold.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10147, 'Agave nectar', NULL, 'Condiments, Sauces & Canned Goods', 'Sweeteners', 'agave nectar syrup sweetener',
    1095, 1825, 1095, 1825,  NULL, NULL, NULL, NULL,  NULL, NULL,
    'Doesn''t need refrigeration. Crystallization is reversible.', 'Manufacturer', NULL),
  (10149, 'Salsa verde', 'tomatillo, refrigerated', 'Deli & Prepared Foods', 'Sauces', 'salsa verde tomatillo green refrigerated mexican',
    NULL, NULL, NULL, NULL,  14, 30, 5, 7,  NULL, NULL,
    'Refrigerated salsa verde has a shorter life than jarred shelf-stable.', 'Manufacturer', NULL),
  (10150, 'Baba ghanoush', NULL, 'Deli & Prepared Foods', 'Refrigerated dips', 'baba ghanoush eggplant tahini dip middle eastern',
    NULL, NULL, NULL, NULL,  7, 10, 5, 7,  NULL, NULL,
    'Drizzle oil on top to prevent oxidation.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10151, 'Tzatziki', NULL, 'Deli & Prepared Foods', 'Refrigerated dips', 'tzatziki greek yogurt cucumber dip',
    NULL, NULL, NULL, NULL,  7, 10, 5, 7,  NULL, NULL,
    'Cucumber releases water — drain off the pooled liquid before serving.', 'Extension', 'https://extension.psu.edu/food-safety'),
  -- Frozen produce / desserts
  (10153, 'Plant-based ice cream', 'coconut, oat, or almond base', 'Food Purchased Frozen', 'Frozen desserts', 'plant based ice cream coconut oat almond vegan',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  60, 180,
    'Ice crystals on the surface mean it''s been thawed and refrozen.', 'Manufacturer', NULL),
  (10154, 'Sorbet', NULL, 'Food Purchased Frozen', 'Frozen desserts', 'sorbet fruit frozen dessert dairy free',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  60, 180,
    'Fruit purée + sugar — same handling as ice cream.', 'Manufacturer', NULL),
  (10155, 'Frozen smoothie pack', NULL, 'Food Purchased Frozen', 'Frozen prepared', 'frozen smoothie pack acai blend fruit',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  180, 270,
    'Blend directly from frozen with liquid.', 'Manufacturer', NULL),
  (10156, 'Mochi ice cream', NULL, 'Food Purchased Frozen', 'Frozen desserts', 'mochi ice cream japanese rice dessert',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  60, 180,
    'Let sit at room temp 3-5 minutes before eating.', 'Manufacturer', NULL),
  (10157, 'Frozen banana', 'homemade for smoothies', 'Food Purchased Frozen', 'Frozen produce', 'frozen banana smoothie home frozen',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  90, 180,
    'Peel before freezing — frozen banana peels are nearly impossible to remove.', 'Extension', 'https://extension.psu.edu/food-safety'),
  (10158, 'Frozen mango chunks', NULL, 'Food Purchased Frozen', 'Frozen produce', 'frozen mango chunks fruit smoothie',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  180, 365,
    'Higher fiber content holds texture well after thawing.', 'Manufacturer', NULL),
  (10159, 'Frozen riced cauliflower', NULL, 'Food Purchased Frozen', 'Frozen produce', 'frozen riced cauliflower low carb',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  180, 365,
    'Cook from frozen — thawing makes it watery.', 'Manufacturer', NULL),
  (10160, 'Frozen edamame', 'in pod or shelled', 'Food Purchased Frozen', 'Frozen produce', 'frozen edamame soybean japanese snack',
    NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL,  180, 365,
    'Steam or boil from frozen for 4-5 minutes.', 'Manufacturer', NULL)
on conflict (id) do nothing;

-- 3. Sanity check (manual; run separately):
--    SELECT count(*) FROM foodkeeper_shelf_life;  -- expect ~782 (660 FK + 122 extended)
--    SELECT source, count(*) FROM foodkeeper_shelf_life GROUP BY source ORDER BY 2 DESC;
--    SELECT * FROM foodkeeper_shelf_life WHERE source = 'Extension' LIMIT 5;
